config/routes.rb
Rails.application.routes.draw do
  root  'homes#top'
  get 'homes/top'
  get "home/about" => "homes#about", as:'about'
  devise_for :users
  resources :books, only: [:index, :show, :create,:destroy,:edit, :update]
  resources :users, only: [:index, :show, :create,:destroy,:edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  validates :name, length: { minimum: 2, maximum: 20},uniqueness: true
  validates :introduction, length: { maximum: 50}
  has_one_attached :profile_image
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [ :edit, :update, :destroy ]
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
end

  def show 
    @book_new =Book.new
    @book = Book.find(params[:id])  
    @user = current_user
    @book_user = @book.user
  end
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Book was successfully deleted."
  end
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def destroy
    # ログアウト時の処理
    reset_session  # セッションを破棄
  
    flash[:notice] = "Signed out successfully."
    redirect_to users_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [ :edit, :update ]
def show
  @book =Book.new
  @user = User.find(params[:id])
  @user_books = @user.books
  @book_user = @user # 記事の投稿者情報を取得
end

def edit
  @user = User.find(params[:id])
end
def update
  @user = User.find(params[:id])
  if @user.update(user_params)
  flash[:notice] = "You have updated user successfully."
  redirect_to user_path(@user)  
  else
    render 'edit'
  end
end
def index
  @user = current_user
  @book = Book.new
  @users = User.all
end

private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end
def is_matching_login_user
  user = User.find(params[:id])
  unless user.id == current_user.id
    redirect_to user_path(current_user.id)
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_saidebar.html.erb
<h1>User info</h1>
<p><%= image_tag user.get_profile_image(100,100) %></p>
<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th>  <%= user.name %> </th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th> <%= user.introduction %> </th>
  </tr>
</tbody></table>

<%= link_to edit_user_path(user), class: "btn btn-secondary w-100" do %>
  <i class="fas fa-user-cog"></i>
  <% end %>

<h1>New book</h1>
<%= form_with model: book do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book',class: "btn btn-success" %>
<% end %>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Update Book" %>
  </br>
  <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
  </div>
  <div class="row"></div>
  </div>
<% end %>

app/views/books/index.html.erb
<%= flash[:notice] %>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
<div class="col-md-3">
<%= render 'saidebar', book: @book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table">

  <thead>
  <tr>
  <th>Title</th>
  <th>Opinion</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
  <td><%= link_to(user_path(book.user)) do %>
    <%= image_tag book.user.get_profile_image(100,100) %>
    <% end %></td>

  <td><%= link_to book.title, book_path(book.id) %></td>

  
  <td><%= book.body %></td>
  </tr>
<% end %>
</table>
</div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="row">
<div class="col-md-3">
<%= render 'saidebar', book: @book_new, user: @book_user %>
</div>
<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
<tbody>
<tr>
<td>
  <%= link_to user_path(@book_user) do %>
    <%= image_tag @book_user.get_profile_image(100,100) %><br>
    <%= @book_user.name %>
  <% end %>
</td>


<td><%= link_to @book.title, book_path(@book) %></td>

<td><%= @book.body %></td>
<% if @book.user == current_user %>
<td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success" %></td>
<td><%= link_to 'Destroy', book_path(@book), class: "btn btn-danger" , method: :delete, data: { confirm: '本当に消しますか?' } %></td>
<% end %>
</tr>
</tbody>
</table>
</div>
</div>

app/views/homes/about.html.erb
<div class="row">
<h1 class="px-3 mx-auto">welcome to<i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="row">
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to<i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
<p>"In"<i class="fa-solid fa-book"></i><strong>Bookers</strong>","</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
<div class="row">
<%= link_to 'Log in', new_user_session_path ,class: "btn btn-primary" %>
</div>
<div class="row">
<%= link_to 'Sign up', new_user_registration_path ,class: "btn btn-success" %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f4307fd5fb.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to  "Bookers","/" ,class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>  
         <li>
            <%= link_to user_path(current_user.id) ,class:"nav-link text-light" do %>
              <i class="fa-solid fa-home"></i>  Home
            <% end %>          
         </li>
          <li>
            <%= link_to users_path ,class:"nav-link text-light" do %>
              <i class="fa-solid fa-users"></i>  Users<% end %>          
          </li>
          <li>
            <%= link_to books_path ,class:"nav-link text-light" do %>
              <i class="fa-solid fa-book-open"></i>  Books<% end %>          </li>
          <li>
          <li>
          <%= link_to destroy_user_session_path, method: :delete,class:"nav-link text-light" do %>
            <i class="fa-solid fa-sign-out-alt"></i>  Log out<% end %>          </li>
        <% else %>
          <li>
            <%= link_to "/" ,class:"nav-link text-light" do %>
              <i class="fa-solid fa-home"></i>  Home<% end %>          </li>
          <li>
            <%= link_to "/home/about" ,class:"nav-link text-light" do %>
              <i class="fa-solid fa-link"></i>  About<% end %>          </li>
          <li>
            <%= link_to "/users/sign_up" ,class:"nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i>  Sign up<% end %>          </li>
          <li>
            <%= link_to "/users/sign_in" ,class:"nav-link text-light" do %>
              <i class="fa-solid fa-sign-in-alt"></i>  Log in<% end %>          </li>
        <% end %>
    
          
        </ul>
      </div>
    </div>
  </nav>
</header>
<div class="container">

  <%= yield %>
  </div>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  
  </body>
</html>

app/views/users/edit.html.erb
<div class="row">
<div class="col-sm-12 col-md8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>User info</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with model: @user do |f| %>

  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.file_field :profile_image, accept: "image/*" %>
  
  <h4>introduction</h4>
  <%= f.text_area :introduction %>
  
  <br><%= f.submit 'Update User',class:"btn btn-secondary" %></br>
  
<% end %>
</div>
</div>

app/views/users/index.html.erb
<%= flash[:notice] %>
<div class="row">
<div class="col-md-3">
<%= render 'books/saidebar', book: @book, user: @user %>
</div>
<div class="col-md-8 offset-md-1">
<h1>Users</h1>
<table class="table">

  <thead>
  <tr>
  <th>image</th>
  <th>name</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
  <td><%= image_tag user.get_profile_image(100,100) %></td>

  <td><%= user.name %></td>

  <td><%= link_to 'Show', user_path(user) %></td>
  </tr>
<% end %>
</table>
</div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="row">
<div class="col-md-3">
<%= render 'books/saidebar', book: @book, user: @user %>
</div>
<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table">

  <thead>
  <tr>
  <th>Title</th>
  <th>Opinion</th>
  </tr>
  </thead>
  <tbody>
  <% @user_books.each do |book| %>
    <tr>
    <td><%= link_to(user_path(book.user)) do %>
      <%= image_tag book.user.get_profile_image(100, 100) %>
    <% end %></td>
  

  <td><%= link_to book.title, book_path(book.id) %></td>

  
  <td><%= book.body %></td>
  </tr>
<% end %>
</table>
</div>
</div>